# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitcoin_crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('private', models.CharField(blank=True, default='', max_length=500)),
                ('public', models.CharField(blank=True, default='', max_length=500)),
                ('words', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='TransactionPaidSystem',
        ),
        migrations.DeleteModel(
            name='TransactionPaidUser',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_from',
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='addresses',
            field=models.ManyToManyField(to='bitcoin_crypto.WalletAddress'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
