# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0003_auto_20180301_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='address',
            new_name='addresses',
        ),
    ]
