# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitcoin_crypto', '0005_pendingtransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('private', models.CharField(blank=True, default='', max_length=500)),
                ('public', models.CharField(blank=True, default='', max_length=500)),
                ('words', models.CharField(blank=True, default='', max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('addresses', models.ManyToManyField(to='bitcoin_crypto.WalletAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
