# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0006_vaultwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, default='withdraw', max_length=200),
        ),
    ]
