# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0008_vaulttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
