# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0009_auto_20180309_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaulttransaction',
            name='to_user',
        ),
        migrations.AlterField(
            model_name='vaulttransaction',
            name='transaction_type',
            field=models.CharField(blank=True, default='to_vault', max_length=200),
        ),
        migrations.AlterField(
            model_name='vaulttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
