# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bitcoin_crypto', '0010_auto_20180315_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimunCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_limit', models.CharField(default='0.0', max_length=200)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
