# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0011_minimuncoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='minimuncoin',
            name='low_limit_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='minimuncoin',
            name='user_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
