# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0012_auto_20180316_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaulttransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
