# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0014_watchonlyaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaulttransaction',
            name='transaction_from',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
