# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitcoin_crypto', '0015_vaulttransaction_transaction_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTaxRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_rate', models.FloatField(blank=True, default=None, null=True)),
                ('current_rate', models.FloatField(default=0)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_form', models.CharField(max_length=5)),
                ('exchange_to', models.CharField(max_length=5)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('limit', models.FloatField()),
                ('order_type', models.CharField(choices=[('0', 'Buy'), ('1', 'sell')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SGDWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderbook',
            unique_together=set([('user', 'order_type')]),
        ),
    ]
