# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0019_auto_20180402_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='order_mode',
            field=models.CharField(choices=[('0', 'market'), ('1', 'limit'), ('2', 'stop-limit')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
