# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0019_auto_20180402_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransactions',
            name='transaction_fee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mining_fee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_fee',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
