# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0020_orderbook_order_mode'),
        ('bitcoin_crypto', '0020_auto_20180404_1303'),
    ]

    operations = [
    ]
