# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0021_merge_20180404_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaulttransaction',
            name='mining_fee',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
    ]
