# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0022_vaulttransaction_mining_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mining_fee',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_fee',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
