# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0024_auto_20180416_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_transaction_count', models.CharField(max_length=128)),
            ],
        ),
    ]
