# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0027_auto_20180504_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifiation',
            new_name='notification',
        ),
    ]
