# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0028_auto_20180504_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
