# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0030_orderbook_maker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='coins_received',
            new_name='coins_covered',
        ),
        migrations.RemoveField(
            model_name='orderbook',
            name='maker',
        ),
    ]
