# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0031_auto_20180524_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='trading_fee',
            field=models.FloatField(default=0),
        ),
    ]
