# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0032_orderbook_trading_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
