# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bitcoin_crypto', '0033_orderbook_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_price', models.FloatField(default=0)),
                ('cahnge_24hr', models.FloatField(default=0)),
                ('height_24hr', models.FloatField(default=0)),
                ('low_24hr', models.FloatField(default=0)),
                ('volume_24hr', models.FloatField(default=0)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
