# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0036_ordermatchinghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermatchinghistory',
            old_name='amount',
            new_name='coins_covered',
        ),
        migrations.AddField(
            model_name='ordermatchinghistory',
            name='matching_price',
            field=models.FloatField(default=0),
        ),
    ]
