# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0037_auto_20180528_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermatchinghistory',
            name='matched_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_order', to='bitcoin_crypto.OrderBook'),
        ),
        migrations.AlterField(
            model_name='ordermatchinghistory',
            name='processing_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_order', to='bitcoin_crypto.OrderBook'),
        ),
    ]
