# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0042_auto_20181024_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingpair',
            old_name='tradingpair',
            new_name='basepair',
        ),
    ]
