# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0043_auto_20181206_0405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tradingpair',
            new_name='CryptoCurrency',
        ),
    ]
