# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0044_auto_20181206_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topair', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
