# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0045_fiat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
