# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0049_auto_20181214_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmfiattransaction',
            name='crypt_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
