# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0051_auto_20181214_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmfiattransaction',
            name='crypto_type',
            field=models.CharField(max_length=5),
            preserve_default=False,
        ),
    ]
