# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0052_confirmfiattransaction_crypto_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmfiattransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitcoin_crypto.OrderBook'),
            preserve_default=False,
        ),
    ]
