# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitcoin_crypto', '0054_auto_20181217_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmCrytpoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('crypto_amount', models.FloatField()),
                ('fiat_type', models.CharField(max_length=5)),
                ('crypto_type', models.CharField(max_length=5)),
                ('receive_address', models.CharField(max_length=128)),
                ('is_confirm', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitcoin_crypto.OrderBook')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_crypto_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_crypto_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='confirmfiattransaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fiat_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='confirmfiattransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fiat_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
