# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0055_auto_20181218_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmcrytporequest',
            name='receive_address',
        ),
    ]
