# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0057_confirmfiattransaction_is_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmcrytporequest',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
