# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 03:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitcoin_crypto', '0058_confirmcrytporequest_is_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCoverTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitcoin_crypto.OrderBook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
