# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0059_ordercovertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='is_otc',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
