# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0060_orderbook_is_otc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='is_otc',
            field=models.CharField(max_length=2),
        ),
    ]
