# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bitcoin_crypto', '0061_auto_20190117_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price_limit', models.CharField(default='0.0', max_length=200)),
                ('max_price_limit', models.CharField(default='0.0', max_length=200)),
                ('min_amount_limit', models.CharField(default='0.0', max_length=200)),
                ('max_amount_limit', models.CharField(default='0.0', max_length=200)),
                ('user_alert', models.BooleanField(default=True)),
                ('low_limit_alert', models.BooleanField(default=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
