# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0062_marketlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketlimit',
            name='low_limit_alert',
        ),
        migrations.RemoveField(
            model_name='marketlimit',
            name='site',
        ),
        migrations.RemoveField(
            model_name='marketlimit',
            name='user_alert',
        ),
    ]
