# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitcoin_crypto', '0063_auto_20190427_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_page', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('client_phonenumber', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defender_user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
