# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0068_pendingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
