# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0069_pendingorder_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_order', to='bitcoin_crypto.OrderBook'),
        ),
    ]
