# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_crypto', '0070_auto_20190611_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmfiattransaction',
            name='pending_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitcoin_crypto.PendingOrder'),
            preserve_default=False,
        ),
    ]
