# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('maker', 'Maker'), ('taker', 'Taker'), ('withdrawal', 'Withdrawal')], max_length=200, unique=True)),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionFeeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.CharField(choices=[('less than', 'Less Than'), ('greater than or equal to', 'Greater Than or Equal To')], max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('fees', models.CharField(max_length=200)),
                ('transaction_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.TransactionFee')),
            ],
        ),
    ]
