# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 08:37
from __future__ import unicode_literals

import apps.fees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_transactionfee_transactionfeerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfee',
            name='currency',
            field=models.CharField(choices=[('btc', 'BTC'), ('sgd', 'SGD')], default='btc', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miningfees',
            name='mining_fees',
            field=models.CharField(default='0.0001', max_length=200, validators=[apps.fees.models.validate_decimal]),
        ),
        migrations.AlterField(
            model_name='transactionfeerange',
            name='fees',
            field=models.CharField(max_length=200, validators=[apps.fees.models.validate_decimal]),
        ),
        migrations.AlterField(
            model_name='transactionfeerange',
            name='value',
            field=models.CharField(max_length=200, validators=[apps.fees.models.validate_decimal]),
        ),
    ]
