# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20180328_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfee',
            name='currency',
            field=models.CharField(choices=[('btc', 'BTC'), ('sgd', 'SGD')], max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='fee_type',
            field=models.CharField(choices=[('maker', 'Maker'), ('taker', 'Taker'), ('withdrawal', 'Withdrawal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfee',
            name='rate_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='transactionfee',
            unique_together=set([('currency', 'fee_type')]),
        ),
    ]
