# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_auto_20180403_0610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionfee',
            unique_together=set([]),
        ),
    ]
