# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_auto_20180403_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfeerange',
            name='limit',
            field=models.CharField(choices=[('greater than or equal to', 'Greater Than or Equal To')], default='greater than or equal to', max_length=200),
        ),
    ]
