# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_auto_20180523_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfee',
            name='fee_type',
            field=models.CharField(choices=[('taker', 'Taker'), ('withdrawal', 'Withdrawal')], max_length=200),
        ),
    ]
