# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_auto_20180525_0901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionfee',
            unique_together=set([('rate_type', 'fee_type')]),
        ),
    ]
