"""
Django settings for cryptocurrency project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _
import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SITE_ROOT = os.path.dirname(os.path.realpath(__name__))
LOCALE_PATHS = ( os.path.join(SITE_ROOT, 'locale'), )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6md#6k4_f4w2x@eq=$ucue998yen@)@^9(^_4-gg2t=hq85o3e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'background_task',

    'cryptocurrency',
    'apps.bitcoin_crypto',
    'apps.authentication',
    'apps.fees',
    'apps.api',

    'widget_tweaks',
    'pyotp',
    'celery',
    'openpyxl',
    'pycountry',
    'localflavor',
    'django_user_agents',

    'request_middleware' #for get_request from current thread
]

MIDDLEWARE = [
    'request_middleware.middleware.RequestMiddleware',#for get_request from current thread
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cryptocurrency.middleware.TimezoneMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'cryptocurrency.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cryptocurrency.context_processors.notification_count',
                'cryptocurrency.context_processors.two_factor_authentication'
            ],
        },
    },
]

WSGI_APPLICATION = 'cryptocurrency.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'tixonexchange',
        'USER': 'root',
        'PASSWORD': '~Abcde',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}

#site settings

SITE_ID = 2

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'authentication.User'

AUTHENTICATION_BACKENDS = (
    ('django.contrib.auth.backends.ModelBackend'),
    ('apps.authentication.backends.EmailBackend'),
)

LOGIN_URL = '/auth/login'

LOGIN_REDIRECT_URL = '/dashboard/'

# Application definition
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_PORT = 587

EMAIL_HOST_USER = 'mishekarshov@hotmail.com'
EMAIL_HOST_PASSWORD = 'ECavNt8kzzmfpXLO'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER #'nysochp@gmail.com' #'Bullxchange <support@mail.bullxchange.io>'


TWILIO_ACCOUNT_SID = "ACbae90cbd04fded85bf40a0d5930263db"
TWILIO_AUTH_TOKEN = "f2431913c821a851b522c5e2042e7ac2"
TWILIO_FROM_NUMBER = "+12027514059"

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGES = (
    ('zh-hans', _('Simplified Chinese')),
    ('en-us', _('English')),
    #Simplified Chinese
)

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "staticfiles")]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#Session expirity settings

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30


# Celery settings
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'

CELERY_BEAT_SCHEDULE = {
    'notify_deposit': {
        'task': 'apps.bitcoin_crypto.tasks.notify_deposit',
        'schedule': 30.0,
    },
    'auto_approve_transactions': {
        'task': 'apps.bitcoin_crypto.tasks.auto_approve_transactions',
        'schedule': 120.0,
    },
    'notify_pending_transaction': {
        'task': 'apps.bitcoin_crypto.tasks.notify_pending_transaction',
        'schedule': 10.0,
    }
}