# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_otp',
            field=models.BooleanField(default=True),
        ),
    ]
