# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180221_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_2fa_key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
