# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20180222_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycupload',
            name='id_card',
            field=models.ImageField(upload_to=''),
        ),
    ]
