# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20180222_1045'),
        ('authentication', '0005_user_change_password_date'),
    ]

    operations = [
    ]
