# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_merge_20180222_1116'),
        ('authentication', '0006_auto_20180222_1611'),
    ]

    operations = [
    ]
