# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_merge_20180222_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_proof', models.FileField(upload_to='')),
                ('photo_selfi', models.ImageField(upload_to='')),
                ('double_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=200)),
                ('last_name', models.CharField(blank=True, default='', max_length=200)),
                ('nationality', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=200)),
                ('country_of_residence', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('zip_code', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='kycupload',
            old_name='id_card',
            new_name='back_page',
        ),
        migrations.RenameField(
            model_name='kycupload',
            old_name='pan_card',
            new_name='front_page',
        ),
        migrations.RemoveField(
            model_name='kycupload',
            name='bank_details',
        ),
        migrations.AddField(
            model_name='kycupload',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='kycupload',
            name='document_type',
            field=models.CharField(choices=[('id', 'ID Card'), ('pan', 'Pan Card')], default='hi', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressproof',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
