# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20180223_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycupload',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
