# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20180224_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('not-verified', 'Not Verified'), ('processing', 'Processing'), ('verified', 'Verified')], default='not-verified', max_length=20),
        ),
    ]
