# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_kyc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kyc_status',
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_verified',
            field=models.CharField(choices=[('not-verified', 'Not Verified'), ('processing', 'Processing'), ('verified', 'Verified')], default='not-verified', max_length=20),
        ),
    ]
