# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20180224_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallets',
            field=models.ManyToManyField(default='btc', to='authentication.Wallet'),
        ),
    ]
