# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 05:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20180224_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressproof',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_address_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kycupload',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
