# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20180226_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallets',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
