# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_merge_20180227_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycupload',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
