# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20180227_1120'),
        ('authentication', '0019_auto_20180227_1152'),
    ]

    operations = [
    ]
