# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_auto_20180420_0630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='previouspassword',
            unique_together=set([]),
        ),
    ]
