# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20180423_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_verified',
            field=models.CharField(choices=[('not-verified', 'Not Verified'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not-verified', max_length=20),
        ),
    ]
