# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20180507_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=128, verbose_name='Your name on your bank account')),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('saving', 'Saving')], max_length=50)),
                ('account_number', models.CharField(max_length=50, verbose_name='Bank Account Number')),
                ('swif_number', models.CharField(max_length=128, verbose_name='SWIF Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
