# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=30, verbose_name='Bank Account Number'),
        ),
    ]
