# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_auto_20180508_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='swif_number',
            field=models.CharField(max_length=20, verbose_name='SWIFT Number'),
        ),
    ]
