# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_accesslog_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
