# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_auto_20180530_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_address', models.CharField(max_length=128, verbose_name='Paypal address')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
