# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_auto_20190302_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alipayaccount',
            old_name='alipay_account',
            new_name='alipay_name',
        ),
        migrations.AddField(
            model_name='alipayaccount',
            name='alipay_number',
            field=models.CharField(default='', max_length=128, verbose_name='Alipay account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alipayaccount',
            name='alipay_qr',
            field=models.ImageField(default='', upload_to='static/qr_uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wechataccount',
            name='wechat_qr',
            field=models.ImageField(upload_to='static/qr_uploads'),
        ),
    ]
