# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0039_auto_20190304_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_type',
        ),
    ]
