# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_remove_bankaccount_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressproof',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country_of_residence',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.DeleteModel(
            name='AddressProof',
        ),
    ]
