# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_auto_20190417_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='swift_number',
        ),
    ]
