# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-13 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0042_remove_bankaccount_swift_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
